#!/usr/bin/env bash

set -e

function print_help() {
    echo "Usage: $0 -t [pitfttype]"
    echo "    -h            Print this help"
    echo "    -t [type]     Specify the type of PiTFT: '28r' (PID 1601) or '28c' (PID 1983) or '35r' or '22'"
    echo
    echo "You must specify a type of display."
    exit 1
}

args=$(getopt -uo 'ht:i:' -- $*)
[ $? != 0 ] && print_help
set -- $args

for i
do
      case "$i"
      in
            -h)
                    print_help
                    ;;
            -t)
                    pitfttype="$2"
                    echo "Type = ${2}"
                    shift
                    shift
                    ;;
            -i)
                    target_image="$2"
                    echo "Image = ${2}"
                    shift
                    shift
                    ;;
      esac
done

if [[ $EUID -ne 0 ]]; then
    echo "chroot-install must be run as root. try: sudo chroot-install"
    exit 1
fi

if  [ "${pitfttype}" != "28r" ] && [ "${pitfttype}" != "28c" ] && [ "${pitfttype}" != "35r" ] && [ "${pitfttype}" != "22" ]
then
        echo "Type must be '28r' (2.8\" resistive, PID 1601) or '28c' (2.8\" capacitive, PID 1983)  or '35r' (3.5\" Resistive) or '22' (2.2\" no touch)"
        print_help
fi

echo "mounting $target_image on /media/raspbian-target"
kpartx -av $target_image
mkdir -p /media/raspbian-target
mount /dev/mapper/loop0p2 /media/raspbian-target
mount /dev/mapper/loop0p1 /media/raspbian-target/boot



echo "unmounting $target_image"
umount /media/raspbian-target/boot
umount /media/raspbian-target
kpartx -d $target_image
